### ISSUE TITLE
-nicole & brandon

### ISSUE THREAD

**Issue by nicolecheng** [RichardzWang/login#1]
nice job! it works and your code is beautiful.
we made an account without a user/pass, so now we can log in w/ blank fields

u:              (blank)
p:              (blank)
result: login successful

u:               (blank)
p: n
result: username not found

points for commenting and naming your main file "app.py"
modules are nice
the template is minimalistic, but gets the job done simply!

**Comment by RichardzWang** [comment]
Fixed! There is now a minimum number of characters required for the username and password.  Thanks!
